// frontendvue/src/components/Navbar.vue
<!-- src/components/Navbar.vue -->
<script setup>
import { useContext } from "vue";
import { useRouter, RouterLink } from "vue-router";
import { inject } from "vue";

// Supongo que estás usando provide/inject para Auth
const authContext = inject("authContext");
const router = useRouter();

const handleLogout = () => {
  authContext.logout();
  router.push("/login");
};
</script>

<template>
  <nav class="navbar navbar-expand navbar-dark bg-dark px-3">
    <RouterLink class="navbar-brand" to="/">Optimizacion y Logistica</RouterLink>

    <div class="navbar-nav me-auto">
      <RouterLink class="nav-link" to="/trabajadores">Trabajadores</RouterLink>
      <RouterLink class="nav-link" to="/asistencias">Asistencias</RouterLink>
      <RouterLink class="nav-link" to="/accidentes">Accidentes</RouterLink>
      <RouterLink class="nav-link" to="/eficiencias"> Eficiencia</RouterLink>
      <RouterLink class="nav-link" to="/desempenos">Desempeño</RouterLink>

      <!-- luego agregaremos Accidentes, Eficiencias, etc. -->
    </div>

    <span class="navbar-text text-white me-3">
      Hola, {{ authContext.auth.username }}
    </span>

    <button class="btn btn-outline-light btn-sm" @click="handleLogout">
      Salir
    </button>
  </nav>
</template>

// frontendreact/src/components/Navbar.jsx
// src/components/Navbar.jsx
import React, { useContext } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AuthContext } from "../App";

export default function Navbar() {
  const { auth, logout } = useContext(AuthContext);
  const navigate = useNavigate();

  const handleLogout = () => {
    logout();
    navigate("/login");
  };

  return (
    <nav className="navbar navbar-expand navbar-dark bg-dark px-3">
      <Link className="navbar-brand" to="/">
        Optimizacion y Logistica
      </Link>

      <div className="navbar-nav me-auto">
        <Link className="nav-link" to="/trabajadores">
          Trabajadores
        </Link>
        <Link className="nav-link" to="/asistencias">
          Asistencias
        </Link>
         <Link className="nav-link" to="/accidentes">
          Accidentes
         </Link>
         <Link className="nav-link" to="/eficiencias">
          Eficiencias
         </Link>
         <Link className="nav-link" to="/desempenos">
           Desempeños
         </Link>  
      </div>

      <span className="navbar-text text-white me-3">
        Hola, {auth.username}
      </span>

      <button className="btn btn-outline-light btn-sm" onClick={handleLogout}>
        Salir
      </button>
    </nav>
  );
}
